/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : Bootloader.c
*  Description  : Main Program
*  Creation Date: 2026-01-04
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include <stdbool.h>

void main(void);

/* ポーリング方式の送信関数 */
static void uart_send_polling(const char *str)
{
    while (*str) {
        /* Wait for transmit data register empty */
        while (SCI9.SSR.BIT.TDRE == 0);
        
        /* Write data */
        SCI9.TDR = (uint8_t)*str;
        
        /* Clear TDRE flag */
        SCI9.SSR.BIT.TDRE = 0;
        
        str++;
    }
    
    /* Wait for transmission complete */
    while (SCI9.SSR.BIT.TEND == 0);
}

/* アプリケーションジャンプ関数 */
static void jump_to_application(void)
{
    void (*app_entry)(void);
    
    uart_send_polling("\r\nJumping to Application...\r\n");
    
    /* アプリケーションの開始アドレス（.textセクションの先頭 = PowerON_Reset） */
    #define APP_START_ADDR   0xFFC20000
    
    /* アプリケーションの先頭4バイトをチェック（有効なRX命令であること） */
    uint32_t first_instruction = *(uint32_t *)APP_START_ADDR;
    if (first_instruction == 0xFFFFFFFF || first_instruction == 0x00000000) {
        uart_send_polling("ERROR: No application found!\r\n");
        return;
    }
    
    /* SCI9を停止 */
    SCI9.SCR.BYTE = 0x00;
    
    /* 割り込みを無効化 */
    __builtin_rx_clrpsw('I');
    
    /* アプリケーションの先頭にジャンプ */
    app_entry = (void (*)(void))APP_START_ADDR;
    app_entry();
}

void main(void)
{
    volatile uint32_t counter = 0;
    volatile uint32_t timeout = 0;
    
    /* SCI9 初期化（割り込み無効） */
    R_Config_SCI9_Create();
    /* R_Config_SCI9_Start() を呼ばない（割り込み有効化しない） */
    
    /* 手動で TE/RE を有効化 */
    SCI9.SCR.BYTE = 0x30U;  /* TE=1, RE=1, 割り込み無効 */
    
    /* 起動メッセージ送信 */
    uart_send_polling("\r\n========================================\r\n");
    uart_send_polling("  RX72N Bootloader (Polling Mode)\r\n");
    uart_send_polling("  SCI9 UART @ 115200bps\r\n");
    uart_send_polling("========================================\r\n");
    uart_send_polling("Press 'U' to enter update mode...\r\n");
    uart_send_polling("Auto-boot in 3 seconds...\r\n");
    
    /* 3秒間入力待ち（簡易タイムアウト） */
    while (timeout < 30000000) {
        timeout++;
        
        /* UART受信チェック */
        if (SCI9.SSR.BIT.RDRF == 1) {
            uint8_t rx_data = SCI9.RDR;
            SCI9.SSR.BIT.RDRF = 0;
            
            if (rx_data == 'U' || rx_data == 'u') {
                uart_send_polling("\r\n*** UPDATE MODE ***\r\n");
                uart_send_polling("Firmware update not implemented yet.\r\n");
                /* TODO: ファームウェア更新処理 */
                while(1);
            }
        }
    }
    
    /* アプリケーションにジャンプ */
    jump_to_application();
    
    /* ジャンプ失敗時 */
    uart_send_polling("Failed to start application!\r\n");
    while (1) {
        counter++;
        if (counter > 10000000) {
            counter = 0;
            uart_send_polling("Bootloader running...\r\n");
        }
    }
}