// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fullmoni

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ImgTacho;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_ImgWarnMaster;
extern lv_obj_t * ui_ImgWarnOilPress;
extern lv_obj_t * ui_ImgWarnWater;
extern lv_obj_t * ui_ImgWarnExhaust;
extern lv_obj_t * ui_ImgWarnBattery;
extern lv_obj_t * ui_ImgWarnBrake;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_ImgWarnFuel;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_ArcRPM;
extern lv_obj_t * ui_imageRPM;
extern lv_obj_t * ui_LblWaterTemp;
extern lv_obj_t * ui_LblIAT;
extern lv_obj_t * ui_LblOilTemp;
extern lv_obj_t * ui_LblMAP;
extern lv_obj_t * ui_LblOilPress;
extern lv_obj_t * ui_LblBattery;
extern lv_obj_t * ui_BarWaterTemp;
extern lv_obj_t * ui_BarIAT;
extern lv_obj_t * ui_BarOilTemp;
extern lv_obj_t * ui_BarMAP;
extern lv_obj_t * ui_BarOilPress;
extern lv_obj_t * ui_BarBattery;
extern lv_obj_t * ui_LblRPM;
extern lv_obj_t * ui_MAPChart;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

