// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fullmoni

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ImgTacho = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_ImgWarnMaster = NULL;
lv_obj_t * ui_ImgWarnOilPress = NULL;
lv_obj_t * ui_ImgWarnWater = NULL;
lv_obj_t * ui_ImgWarnExhaust = NULL;
lv_obj_t * ui_ImgWarnBattery = NULL;
lv_obj_t * ui_ImgWarnBrake = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_ImgWarnFuel = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_ArcRPM = NULL;
lv_obj_t * ui_imageRPM = NULL;
lv_obj_t * ui_LblWaterTemp = NULL;
lv_obj_t * ui_LblIAT = NULL;
lv_obj_t * ui_LblOilTemp = NULL;
lv_obj_t * ui_LblMAP = NULL;
lv_obj_t * ui_LblOilPress = NULL;
lv_obj_t * ui_LblBattery = NULL;
lv_obj_t * ui_BarWaterTemp = NULL;
lv_obj_t * ui_BarIAT = NULL;
lv_obj_t * ui_BarOilTemp = NULL;
lv_obj_t * ui_BarMAP = NULL;
lv_obj_t * ui_BarOilPress = NULL;
lv_obj_t * ui_BarBattery = NULL;
lv_obj_t * ui_LblRPM = NULL;
lv_obj_t * ui_MAPChart = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgTacho = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgTacho, &ui_img_back5_png);
    lv_obj_set_width(ui_ImgTacho, LV_SIZE_CONTENT);   /// 340
    lv_obj_set_height(ui_ImgTacho, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_ImgTacho, 86);
    lv_obj_set_y(ui_ImgTacho, -2);
    lv_obj_set_align(ui_ImgTacho, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgTacho, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgTacho, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_back6_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image2, -232);
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgWarnMaster = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgWarnMaster, &ui_img_ws_masterwarning_png);
    lv_obj_set_width(ui_ImgWarnMaster, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_ImgWarnMaster, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_ImgWarnMaster, -385);
    lv_obj_set_y(ui_ImgWarnMaster, -114);
    lv_obj_set_align(ui_ImgWarnMaster, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWarnMaster, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWarnMaster, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgWarnOilPress = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgWarnOilPress, &ui_img_ws_oilpresswarning_png);
    lv_obj_set_width(ui_ImgWarnOilPress, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_ImgWarnOilPress, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_ImgWarnOilPress, -385);
    lv_obj_set_y(ui_ImgWarnOilPress, -83);
    lv_obj_set_align(ui_ImgWarnOilPress, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWarnOilPress, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWarnOilPress, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgWarnWater = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgWarnWater, &ui_img_ws_waterwarning_png);
    lv_obj_set_width(ui_ImgWarnWater, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_ImgWarnWater, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_ImgWarnWater, -385);
    lv_obj_set_y(ui_ImgWarnWater, -51);
    lv_obj_set_align(ui_ImgWarnWater, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWarnWater, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWarnWater, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgWarnExhaust = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgWarnExhaust, &ui_img_ws_exhaustwarning_png);
    lv_obj_set_width(ui_ImgWarnExhaust, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_ImgWarnExhaust, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_ImgWarnExhaust, -385);
    lv_obj_set_y(ui_ImgWarnExhaust, -16);
    lv_obj_set_align(ui_ImgWarnExhaust, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWarnExhaust, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWarnExhaust, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgWarnBattery = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgWarnBattery, &ui_img_ws_batterywarning_png);
    lv_obj_set_width(ui_ImgWarnBattery, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_ImgWarnBattery, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_ImgWarnBattery, -385);
    lv_obj_set_y(ui_ImgWarnBattery, 17);
    lv_obj_set_align(ui_ImgWarnBattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWarnBattery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWarnBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgWarnBrake = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgWarnBrake, &ui_img_ws_breakwarning_png);
    lv_obj_set_width(ui_ImgWarnBrake, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_ImgWarnBrake, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_ImgWarnBrake, -385);
    lv_obj_set_y(ui_ImgWarnBrake, 49);
    lv_obj_set_align(ui_ImgWarnBrake, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWarnBrake, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWarnBrake, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image9, &ui_img_ws_beltwarning_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_Image9, -694);
    lv_obj_set_y(ui_Image9, 31);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgWarnFuel = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgWarnFuel, &ui_img_ws_fuelcheck_png);
    lv_obj_set_width(ui_ImgWarnFuel, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_ImgWarnFuel, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_ImgWarnFuel, -385);
    lv_obj_set_y(ui_ImgWarnFuel, 112);
    lv_obj_set_align(ui_ImgWarnFuel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWarnFuel, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWarnFuel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image11, &ui_img_ws_beltwarning_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_Image11, -385);
    lv_obj_set_y(ui_Image11, 79);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcRPM = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcRPM, 249);
    lv_obj_set_height(ui_ArcRPM, 251);
    lv_obj_set_x(ui_ArcRPM, 40);
    lv_obj_set_y(ui_ArcRPM, -1);
    lv_obj_set_align(ui_ArcRPM, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcRPM, 0, 9000);
    lv_arc_set_value(ui_ArcRPM, 3500);
    lv_arc_set_bg_angles(ui_ArcRPM, 90, 0);
    lv_obj_set_style_arc_color(ui_ArcRPM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcRPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcRPM, lv_color_hex(0xFF4040), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcRPM, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcRPM, 18, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcRPM, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcRPM, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcRPM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_imageRPM = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_imageRPM, &ui_img_marker_red_bar_80x7s_png);
    lv_obj_set_width(ui_imageRPM, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_imageRPM, LV_SIZE_CONTENT);    /// 7
    lv_obj_set_x(ui_imageRPM, 111);
    lv_obj_set_y(ui_imageRPM, -4);
    lv_obj_set_align(ui_imageRPM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageRPM, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imageRPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_imageRPM, -25, 0);
    lv_img_set_angle(ui_imageRPM, 900);
    lv_obj_set_style_transform_angle(ui_imageRPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblWaterTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LblWaterTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblWaterTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblWaterTemp, -179);
    lv_obj_set_y(ui_LblWaterTemp, -98);
    lv_obj_set_align(ui_LblWaterTemp, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_LblWaterTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblWaterTemp, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblIAT = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LblIAT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblIAT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblIAT, -180);
    lv_obj_set_y(ui_LblIAT, -54);
    lv_obj_set_align(ui_LblIAT, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_LblIAT, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblIAT, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblOilTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LblOilTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblOilTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblOilTemp, -180);
    lv_obj_set_y(ui_LblOilTemp, -12);
    lv_obj_set_align(ui_LblOilTemp, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_LblOilTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblOilTemp, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMAP = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LblMAP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblMAP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblMAP, -180);
    lv_obj_set_y(ui_LblMAP, 29);
    lv_obj_set_align(ui_LblMAP, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_LblMAP, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblMAP, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblOilPress = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LblOilPress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblOilPress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblOilPress, -180);
    lv_obj_set_y(ui_LblOilPress, 66);
    lv_obj_set_align(ui_LblOilPress, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_LblOilPress, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblOilPress, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblBattery = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LblBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblBattery, -180);
    lv_obj_set_y(ui_LblBattery, 105);
    lv_obj_set_align(ui_LblBattery, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_LblBattery, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblBattery, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarWaterTemp = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_BarWaterTemp, 0, 120);
    lv_bar_set_value(ui_BarWaterTemp, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarWaterTemp, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarWaterTemp, 102);
    lv_obj_set_height(ui_BarWaterTemp, 18);
    lv_obj_set_x(ui_BarWaterTemp, -255);
    lv_obj_set_y(ui_BarWaterTemp, -100);
    lv_obj_set_align(ui_BarWaterTemp, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BarWaterTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarWaterTemp, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarWaterTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarWaterTemp, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarWaterTemp, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarWaterTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BarWaterTemp, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BarWaterTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BarWaterTemp, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarIAT = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_BarIAT, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarIAT, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarIAT, 102);
    lv_obj_set_height(ui_BarIAT, 18);
    lv_obj_set_x(ui_BarIAT, -255);
    lv_obj_set_y(ui_BarIAT, -56);
    lv_obj_set_align(ui_BarIAT, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BarIAT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarIAT, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarIAT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarIAT, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarIAT, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarIAT, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarOilTemp = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_BarOilTemp, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarOilTemp, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarOilTemp, 102);
    lv_obj_set_height(ui_BarOilTemp, 18);
    lv_obj_set_x(ui_BarOilTemp, -255);
    lv_obj_set_y(ui_BarOilTemp, -16);
    lv_obj_set_align(ui_BarOilTemp, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BarOilTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarOilTemp, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarOilTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarOilTemp, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarOilTemp, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarOilTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarMAP = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_BarMAP, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarMAP, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarMAP, 102);
    lv_obj_set_height(ui_BarMAP, 18);
    lv_obj_set_x(ui_BarMAP, -255);
    lv_obj_set_y(ui_BarMAP, 24);
    lv_obj_set_align(ui_BarMAP, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BarMAP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarMAP, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarMAP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarMAP, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarMAP, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarMAP, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarOilPress = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_BarOilPress, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarOilPress, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarOilPress, 102);
    lv_obj_set_height(ui_BarOilPress, 18);
    lv_obj_set_x(ui_BarOilPress, -255);
    lv_obj_set_y(ui_BarOilPress, 62);
    lv_obj_set_align(ui_BarOilPress, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BarOilPress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarOilPress, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarOilPress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarOilPress, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarOilPress, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarOilPress, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBattery = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_BarBattery, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarBattery, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarBattery, 102);
    lv_obj_set_height(ui_BarBattery, 18);
    lv_obj_set_x(ui_BarBattery, -255);
    lv_obj_set_y(ui_BarBattery, 100);
    lv_obj_set_align(ui_BarBattery, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BarBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBattery, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBattery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarBattery, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBattery, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBattery, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LblRPM = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LblRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblRPM, 82);
    lv_obj_set_y(ui_LblRPM, 34);
    lv_obj_set_align(ui_LblRPM, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_LblRPM, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MAPChart = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_MAPChart, 200);
    lv_obj_set_height(ui_MAPChart, 118);
    lv_obj_set_x(ui_MAPChart, 296);
    lv_obj_set_y(ui_MAPChart, -35);
    lv_obj_set_align(ui_MAPChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_MAPChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_MAPChart, 30);
    lv_chart_set_axis_tick(ui_MAPChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_MAPChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_MAPChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_MAPChart_series_1 = lv_chart_add_series(ui_MAPChart, lv_color_hex(0x808080),
                                                                   LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_MAPChart_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_MAPChart, ui_MAPChart_series_1, ui_MAPChart_series_1_array);
    lv_obj_set_style_bg_color(ui_MAPChart, lv_color_hex(0x201E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MAPChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ImgTacho = NULL;
    ui_Image2 = NULL;
    ui_ImgWarnMaster = NULL;
    ui_ImgWarnOilPress = NULL;
    ui_ImgWarnWater = NULL;
    ui_ImgWarnExhaust = NULL;
    ui_ImgWarnBattery = NULL;
    ui_ImgWarnBrake = NULL;
    ui_Image9 = NULL;
    ui_ImgWarnFuel = NULL;
    ui_Image11 = NULL;
    ui_ArcRPM = NULL;
    ui_imageRPM = NULL;
    ui_LblWaterTemp = NULL;
    ui_LblIAT = NULL;
    ui_LblOilTemp = NULL;
    ui_LblMAP = NULL;
    ui_LblOilPress = NULL;
    ui_LblBattery = NULL;
    ui_BarWaterTemp = NULL;
    ui_BarIAT = NULL;
    ui_BarOilTemp = NULL;
    ui_BarMAP = NULL;
    ui_BarOilPress = NULL;
    ui_BarBattery = NULL;
    ui_LblRPM = NULL;
    ui_MAPChart = NULL;

}
