/*
 * variant_id.h - Auto-generated by switch_design.ps1
 * DO NOT EDIT - This file is regenerated on design switch
 */
#ifndef VARIANT_ID_H_
#define VARIANT_ID_H_

#define BUILD_VARIANT_ID "aw003"
#define BUILD_VARIANT_STRING "VARIANT:aw003"
#define BUILD_DESIGN_ID "eez003"

#endif /* VARIANT_ID_H_ */
