/*
 * variant_id.h - Auto-generated by build_variants.ps1
 * DO NOT EDIT - This file is regenerated on each build
 */
#ifndef VARIANT_ID_H_
#define VARIANT_ID_H_

#define BUILD_VARIANT_ID "aw002"
#define BUILD_VARIANT_STRING "VARIANT:aw002"

#endif /* VARIANT_ID_H_ */