// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fullmoni

#ifndef _FULLMONI_UI_H
#define _FULLMONI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_back5_png);    // assets/Back5.png
LV_IMG_DECLARE(ui_img_marker_red_bar_80x7s_png);    // assets/Marker_red_bar_80x7s.png
LV_IMG_DECLARE(ui_img_marker_red_bar_20x7s_png);    // assets/Marker_red_bar_20x7s.png
LV_IMG_DECLARE(ui_img_back6_png);    // assets/Back6.png
LV_IMG_DECLARE(ui_img_fuel2_png);    // assets/fuel2.png
LV_IMG_DECLARE(ui_img_fuel1_png);    // assets/fuel1.png
LV_IMG_DECLARE(ui_img_fmw_op0_png);    // assets/fmw_op0.png
LV_IMG_DECLARE(ui_img_ws_masterwarning_png);    // assets/ws_masterwarning.png
LV_IMG_DECLARE(ui_img_ws_oilpresswarning_png);    // assets/ws_oilpresswarning.png
LV_IMG_DECLARE(ui_img_ws_watarcool_png);    // assets/ws_watarcool.png
LV_IMG_DECLARE(ui_img_ws_waterwarning_png);    // assets/ws_waterwarning.png
LV_IMG_DECLARE(ui_img_ws_exhaustwarning_png);    // assets/ws_exhaustwarning.png
LV_IMG_DECLARE(ui_img_ws_batterywarning_png);    // assets/ws_batterywarning.png
LV_IMG_DECLARE(ui_img_ws_breakwarning_png);    // assets/ws_breakwarning.png
LV_IMG_DECLARE(ui_img_ws_beltwarning_png);    // assets/ws_beltwarning.png
LV_IMG_DECLARE(ui_img_ws_fuelcheck_png);    // assets/ws_fuelcheck.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_FontHUDmid);
LV_FONT_DECLARE(ui_font_FontHUDsmall);
LV_FONT_DECLARE(ui_font_FontLARGR);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
