// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fullmoni

#include "../ui.h"

// COMPONENT BarWaterTemp

lv_obj_t * ui_BarWaterTemp_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_BarWaterTemp;
    cui_BarWaterTemp = lv_bar_create(comp_parent);
    lv_bar_set_value(cui_BarWaterTemp, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(cui_BarWaterTemp, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_BarWaterTemp, 119);
    lv_obj_set_height(cui_BarWaterTemp, 18);
    lv_obj_set_x(cui_BarWaterTemp, -251);
    lv_obj_set_y(cui_BarWaterTemp, -106);
    lv_obj_set_align(cui_BarWaterTemp, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(cui_BarWaterTemp, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_BarWaterTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_BarWaterTemp, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_BarWaterTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BARWATERTEMP_NUM);
    children[UI_COMP_BARWATERTEMP_BARWATERTEMP] = cui_BarWaterTemp;
    lv_obj_add_event_cb(cui_BarWaterTemp, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_BarWaterTemp, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_BarWaterTemp_create_hook(cui_BarWaterTemp);
    return cui_BarWaterTemp;
}

