// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fullmoni

#ifndef _UI_COMP_BARWATERTEMP_H
#define _UI_COMP_BARWATERTEMP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT BarWaterTemp
#define UI_COMP_BARWATERTEMP_BARWATERTEMP 0
#define _UI_COMP_BARWATERTEMP_NUM 1
lv_obj_t * ui_BarWaterTemp_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
