#!/usr/bin/env python3
"""Replace EEZ-generated ui_image_ui_img_fmw_op0_png.c with flash redirect."""
import pathlib

TARGET = pathlib.Path(__file__).resolve().parent.parent / "Firmware" / "src" / "ui" / "images" / "ui_image_ui_img_fmw_op0_png.c"

CONTENT = """\
/*
 * ui_image_ui_img_fmw_op0_png.c  - PATCHED (flash redirect)
 *
 * EEZ Studio generates this file with embedded pixel data.
 * This patched version redirects to the flash address where
 * imgwrite stores the startup image.
 *
 * Regenerated by EEZ Studio Build -> run tools/patch_eez_flow.py
 */

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
    #include "lvgl.h"
#else
    #include "lvgl/lvgl.h"
#endif

#include "../ui.h"

/* Startup image is written to flash by imgwrite command.
 * Data format: 12-byte header (BM magic + info) followed by RGB565 pixels. */
#define IMAGE_HEADER_SIZE     12
#define STARTUP_IMAGE_PIXEL_ADDR  ((const uint8_t *)(0xFFE20000UL + IMAGE_HEADER_SIZE))

const lv_img_dsc_t img_ui_img_fmw_op0_png = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = 765,
    .header.h           = 256,
    .data_size          = 765u * 256u * 2u,
    .data               = STARTUP_IMAGE_PIXEL_ADDR,
};
"""

if __name__ == "__main__":
    TARGET.write_text(CONTENT, encoding="utf-8")
    print(f"Patched: {TARGET} ({TARGET.stat().st_size} bytes)")
