#!/usr/bin/env python3
"""
EEZ Studio 生成コードのポストプロセス スクリプト

EEZ Studio で Build した後に実行し、以下のパッチを適用する:
1. eez-flow.cpp: LV_USE_CALENDAR=0 のとき Calendar 関連 ACTION をスキップ（stub 関数で代替）
2. eez-flow.cpp: LV_USE_TABVIEW=0 のとき Tabview 関連 ACTION をスキップ（stub 関数で代替）
3. ui_image_ui_img_fmw_op0_png.c: 埋め込みピクセル配列をフラッシュアドレスへリダイレクト

使い方:
  python tools/patch_eez_flow.py
  python tools/patch_eez_flow.py --check   # パッチ済みか確認のみ
"""
import argparse
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
EEZ_FLOW_CPP = SCRIPT_DIR.parent / "Firmware" / "src" / "ui" / "eez-flow.cpp"
EEZ_IMAGE_C = SCRIPT_DIR.parent / "Firmware" / "src" / "ui" / "images" / "ui_image_ui_img_fmw_op0_png.c"

# ---------------------------------------------------------------------------
# パッチ定義
# ---------------------------------------------------------------------------

CALENDAR_STUB = """\
static void calendarSetTodayDate(FlowState *, unsigned, const ListOfAssetsPtr<Property> &, uint32_t) {}
static void calendarSetShowedDate(FlowState *, unsigned, const ListOfAssetsPtr<Property> &, uint32_t) {}
static void calendarSetHighlightedDate(FlowState *, unsigned, const ListOfAssetsPtr<Property> &, uint32_t) {}
static void calendarGetPressedDate(FlowState *, unsigned, const ListOfAssetsPtr<Property> &, uint32_t) {}
#endif /* LV_USE_CALENDAR */"""

TABVIEW_STUB = """\
static void tabviewSetActiveTab(FlowState *, unsigned, const ListOfAssetsPtr<Property> &, uint32_t) {}
static void tabviewGetActiveTab(FlowState *, unsigned, const ListOfAssetsPtr<Property> &, uint32_t) {}
#endif /* LV_USE_TABVIEW */"""

# Calendar: ACTION_START(calendarSetTodayDate) から
#           calendarGetPressedDate の ACTION_END まで
CALENDAR_PATTERN = re.compile(
    r"(ACTION_END\n)"                           # 直前の ACTION_END (createScreen 等)
    r"(ACTION_START\(calendarSetTodayDate\).*?"  # Calendar ブロック開始
    r"ACTION_END\n)"                             # calendarGetPressedDate の ACTION_END
    r"(ACTION_START\(buttonMatrixSetButtonCtrl\))",  # 次のブロック
    re.DOTALL,
)

# Tabview: ACTION_START(tabviewSetActiveTab) から
#          tabviewGetActiveTab の ACTION_END まで
TABVIEW_PATTERN = re.compile(
    r"(ACTION_END\n)"                             # 直前の ACTION_END (buttonMatrixClearButtonCtrl 等)
    r"(ACTION_START\(tabviewSetActiveTab\).*?"     # Tabview ブロック開始
    r"ACTION_END\n)"                               # tabviewGetActiveTab の ACTION_END
    r"(typedef void)",                             # 次の宣言
    re.DOTALL,
)


def is_already_patched(content: str) -> dict:
    """パッチ済みかどうか確認"""
    return {
        "calendar": "#if LV_USE_CALENDAR" in content,
        "tabview": "#if LV_USE_TABVIEW" in content,
    }


def apply_patches(content: str) -> tuple[str, list[str]]:
    """パッチを適用し、(変更後テキスト, 適用パッチ名リスト) を返す"""
    applied = []

    # Calendar パッチ
    if "#if LV_USE_CALENDAR" not in content:
        m = CALENDAR_PATTERN.search(content)
        if m:
            replacement = (
                m.group(1)
                + "#if LV_USE_CALENDAR\n"
                + m.group(2)
                + "#else\n"
                + CALENDAR_STUB + "\n"
                + m.group(3)
            )
            content = content[: m.start()] + replacement + content[m.end() :]
            applied.append("LV_USE_CALENDAR guard")
        else:
            print("WARNING: Calendar パターンが見つかりません。EEZ Studio の出力形式が変わった可能性があります。", file=sys.stderr)

    # Tabview パッチ
    if "#if LV_USE_TABVIEW" not in content:
        m = TABVIEW_PATTERN.search(content)
        if m:
            replacement = (
                m.group(1)
                + "#if LV_USE_TABVIEW\n"
                + m.group(2)
                + "#else\n"
                + TABVIEW_STUB + "\n"
                + m.group(3)
            )
            content = content[: m.start()] + replacement + content[m.end() :]
            applied.append("LV_USE_TABVIEW guard")
        else:
            print("WARNING: Tabview パターンが見つかりません。EEZ Studio の出力形式が変わった可能性があります。", file=sys.stderr)

    return content, applied


# ---------------------------------------------------------------------------
# 起動画像パッチ: 埋め込み配列 → フラッシュアドレス リダイレクト
# ---------------------------------------------------------------------------

IMAGE_REDIRECT_CONTENT = """\
/*
 * ui_image_ui_img_fmw_op0_png.c  - PATCHED (flash redirect)
 *
 * EEZ Studio generates this file with embedded pixel data.
 * This patched version redirects to the flash address where
 * imgwrite stores the startup image.
 *
 * Regenerated by EEZ Studio Build -> run tools/patch_eez_flow.py
 */

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
    #include "lvgl.h"
#else
    #include "lvgl/lvgl.h"
#endif

#include "../ui.h"

/* Startup image is written to flash by imgwrite command.
 * Data format: 12-byte header (BM magic + info) followed by RGB565 pixels. */
#define IMAGE_HEADER_SIZE     12
#define STARTUP_IMAGE_PIXEL_ADDR  ((const uint8_t *)(0xFFE20000UL + IMAGE_HEADER_SIZE))

const lv_img_dsc_t img_ui_img_fmw_op0_png = {
    .header.cf          = LV_IMG_CF_TRUE_COLOR,
    .header.always_zero = 0,
    .header.reserved    = 0,
    .header.w           = 765,
    .header.h           = 256,
    .data_size          = 765u * 256u * 2u,
    .data               = STARTUP_IMAGE_PIXEL_ADDR,
};
"""

IMAGE_PATCH_MARKER = "PATCHED (flash redirect)"


def is_image_patched(path: Path) -> bool:
    """起動画像ファイルがパッチ済みか確認"""
    if not path.exists():
        return False
    return IMAGE_PATCH_MARKER in path.read_text(encoding="utf-8")


def apply_image_patch(path: Path) -> bool:
    """起動画像ファイルをフラッシュリダイレクト版に置換"""
    if is_image_patched(path):
        return False
    path.write_text(IMAGE_REDIRECT_CONTENT, encoding="utf-8")
    return True


def main():
    parser = argparse.ArgumentParser(description="EEZ Studio 生成コードにパッチを適用")
    parser.add_argument("--check", action="store_true", help="パッチ済みか確認のみ（変更しない）")
    parser.add_argument("--file", type=Path, default=EEZ_FLOW_CPP, help="対象ファイルパス")
    args = parser.parse_args()

    target = args.file
    if not target.exists():
        print(f"ERROR: {target} が見つかりません", file=sys.stderr)
        sys.exit(1)

    content = target.read_text(encoding="utf-8")
    status = is_already_patched(content)

    # 起動画像パッチ確認
    image_patched = is_image_patched(EEZ_IMAGE_C)

    if args.check:
        all_patched = all(status.values()) and image_patched
        for name, patched in status.items():
            mark = "OK" if patched else "未適用"
            print(f"  {name}: {mark}")
        print(f"  startup_image: {'OK' if image_patched else '未適用'}")
        sys.exit(0 if all_patched else 1)

    applied_all = []

    # eez-flow.cpp パッチ
    if not all(status.values()):
        content, applied = apply_patches(content)
        if applied:
            target.write_text(content, encoding="utf-8")
            applied_all.extend(applied)

    # 起動画像パッチ
    if apply_image_patch(EEZ_IMAGE_C):
        applied_all.append("startup_image flash redirect")

    if applied_all:
        print(f"パッチ適用完了: {', '.join(applied_all)}")
    else:
        print("既にパッチ適用済みです。")


if __name__ == "__main__":
    main()
