<#
.SYNOPSIS
    Switch the active EEZ design variant (eez001 or eez002).

.DESCRIPTION
    Replaces the directory junctions Firmware/src/ui and Firmware/src/ui_binding
    to point at the selected design folder under Firmware/eez/<design>/.
    Also updates variant_id.h for firmware identification.

.PARAMETER Design
    The design name: eez001 or eez002

.EXAMPLE
    .\switch_design.ps1 -Design eez002
#>
param(
    [Parameter(Mandatory)]
    [ValidateSet('eez001', 'eez002', 'eez003')]
    [string]$Design
)

$ErrorActionPreference = 'Stop'

# Resolve paths
$repoRoot   = Split-Path $PSScriptRoot -Parent
$fwDir      = Join-Path $repoRoot 'Firmware'
$designDir  = Join-Path $fwDir "eez\$Design"
$srcDir     = Join-Path $fwDir 'src'
$uiJunction = Join-Path $srcDir 'ui'
$ubJunction = Join-Path $srcDir 'ui_binding'

# Validate design directory exists
if (-not (Test-Path (Join-Path $designDir 'ui'))) {
    Write-Error "Design directory not found: $designDir\ui"
    exit 1
}
if (-not (Test-Path (Join-Path $designDir 'ui_binding'))) {
    Write-Error "Design directory not found: $designDir\ui_binding"
    exit 1
}

# --- Remove existing junctions ---
foreach ($junc in @($uiJunction, $ubJunction)) {
    if (Test-Path $junc) {
        $item = Get-Item $junc -Force
        if ($item.LinkType -eq 'Junction') {
            cmd /c "rmdir `"$junc`"" 2>$null
        } else {
            Write-Error "$junc exists but is not a junction. Aborting."
            exit 1
        }
    }
}

# --- Create new junctions ---
$uiTarget = Join-Path $designDir 'ui'
$ubTarget = Join-Path $designDir 'ui_binding'

cmd /c "mklink /J `"$uiJunction`" `"$uiTarget`""
cmd /c "mklink /J `"$ubJunction`" `"$ubTarget`""

# --- Update variant_id.h ---
$variantMap = @{
    'eez001' = 'aw001'
    'eez002' = 'aw002'
    'eez003' = 'aw003'
}
$variantId = $variantMap[$Design]
$variantHeader = Join-Path $srcDir 'variant_id.h'
@"
/*
 * variant_id.h - Auto-generated by switch_design.ps1
 * DO NOT EDIT - This file is regenerated on design switch
 */
#ifndef VARIANT_ID_H_
#define VARIANT_ID_H_

#define BUILD_VARIANT_ID "$variantId"
#define BUILD_VARIANT_STRING "VARIANT:$variantId"
#define BUILD_DESIGN_ID "$Design"

#endif /* VARIANT_ID_H_ */
"@ | Set-Content -Path $variantHeader -Encoding UTF8

# --- Show result ---
Write-Host ""
Write-Host "=== Design switched to: $Design ($variantId) ===" -ForegroundColor Green
Write-Host "  ui         -> $($(Get-Item $uiJunction -Force).Target)"
Write-Host "  ui_binding -> $($(Get-Item $ubJunction -Force).Target)"
Write-Host "  variant_id -> $variantId"
Write-Host ""
Write-Host "Run 'Clean (GCC-RX)' then 'Build (GCC-RX)' to rebuild." -ForegroundColor Yellow
