/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.2.2] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
STCAN_MSG tx;
unsigned int RPM, i;
unsigned int SPD,GEAR,TPS;
unsigned int tick;  /* 20ms timer counter (50Hz, matches customer MoTeC) */
unsigned int lfsr;  /* PRNG state for idle RPM jitter */
float THW,THA,OT,BATTV,OP,LA1,MAP;
DataFrame1 sMsgStruct_Frame1;
DataFrame2 sMsgStruct_Frame2;
DataFrame3 sMsgStruct_Frame3;
DataFrame4 sMsgStruct_Frame4;
DataFrame5 sMsgStruct_Frame5;
DataFrame6 sMsgStruct_Frame6;
/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnTimer_updateTimeTick20ms_20( );
void OnMsgName_DataFrame1(DataFrame1 RxMsg);
GCC_EXTERN void GCC_EXPORT OnMsgName_DataFrame1_Wrapper(STCAN_MSG RxMsg);
GCC_EXTERN void GCC_EXPORT OnTimer_incGearPos_1000( );
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER Function Wrapper Prototype  */
void OnMsgName_DataFrame1_Wrapper(STCAN_MSG RxMsg){ OnMsgName_DataFrame1(&RxMsg); }
/* End BUSMASTER Function Wrapper Prototype  */


/* Start BUSMASTER generated function - OnTimer_updateTimeTick20ms_20 */
void OnTimer_updateTimeTick20ms_20( )
{
tick++;

/* Simple 16-bit LFSR for RPM jitter (period 65535) */
if(lfsr == 0) lfsr = 0xACE1;
{unsigned int bit = ((lfsr >> 0) ^ (lfsr >> 2) ^ (lfsr >> 3) ^ (lfsr >> 5)) & 1;
lfsr = (lfsr >> 1) | (bit << 15);}

/* Phase 0: Accel (0-250 tick = 0-5s) */
if(tick <= 250){
	RPM = (unsigned int)(3000.0 * tick / 250);
	SPD = (unsigned int)(60.0 * tick / 250);
	TPS = (unsigned int)(50.0 * tick / 250);  /* 0->50 (0->5%) */
	GEAR = 3;
}
/* Phase 1: Cruise (250-750 tick = 5-15s) */
else if(tick <= 750){
	RPM = 3000;
	SPD = 60;
	TPS = 20;  /* cruise 2% */
	GEAR = 5;
}
/* Phase 2: Decel->Stop (750-1000 tick = 15-20s) */
else if(tick <= 1000){
	RPM = 3000 - (unsigned int)(2170.0 * (tick - 750) / 250);
	SPD = 60 - (unsigned int)(60.0 * (tick - 750) / 250);
	TPS = 5;  /* decel 0.5% */
	GEAR = (SPD > 30) ? 3 : (SPD > 10) ? 2 : 1;
}
/* Phase 3: Idle (1000~ = 20s~) RPM jitters around 830 like real engine */
/* Customer info: freeze only when TPS value is CHANGING, not when fixed at 0% */
/* TPS stays at 0% during idle - freeze test uses separate TPS variation phase */
else{
	RPM = 810 + (lfsr % 41);
	SPD = 0;
	TPS = 0;  /* idle: 0% */
	GEAR = 0;
}

/* Sensor values (raw for DBC factors) */
/* Phase 3: Water temp rises from 80C to 115C over ~25s after stopping */
/* Simulates real car: no airflow at idle => coolant temp climbs */
if(tick > 1000){
	/* tick 1000-2250 (20s-45s): 800->1150 over 1250 ticks (25s) */
	THW = 800 + (unsigned int)(350.0 * (tick - 1000) / 1250);
	if(THW > 1150) THW = 1150; /* Cap at 115C */
} else {
	THW = 800;    /* Water temp 80C during driving */
}
THA = 400;    /* Intake temp 40C (factor 0.1) */
OT  = 900;    /* Oil temp 90C (factor 0.1) */
OP  = 3000;   /* Oil pressure 300kPa (factor 0.1) */
BATTV = 1400; /* Battery 14.0V (factor 0.01) */
LA1 = 1000;   /* A/F 14.7 (factor 0.0147) */
MAP = (tick > 1000) ? 350 : 1000; /* MAP idle 35kPa / cruise 100kPa */

/* Set to frame and send */
sMsgStruct_Frame1.RPM = RPM;
sMsgStruct_Frame1.ThrottlePosition = TPS;
sMsgStruct_Frame1.ManifolePressure = MAP;
sMsgStruct_Frame1.IntakeAirTemperature = THA;
sMsgStruct_Frame2.EngineTemp = THW;
sMsgStruct_Frame2.Lambda1 = LA1;
sMsgStruct_Frame3.OilTemp = OT;
sMsgStruct_Frame4.OilPressure = OP;
sMsgStruct_Frame4.BatteryVoltage = BATTV;
sMsgStruct_Frame5.GroundSpeed = SPD;
sMsgStruct_Frame6.GearPosition = GEAR;

SendMsg(sMsgStruct_Frame1);
SendMsg(sMsgStruct_Frame2);
SendMsg(sMsgStruct_Frame3);
SendMsg(sMsgStruct_Frame4);
SendMsg(sMsgStruct_Frame5);
SendMsg(sMsgStruct_Frame6);
}/* End BUSMASTER generated function - OnTimer_updateTimeTick20ms_20 */
/* Start BUSMASTER generated function - OnMsgName_DataFrame1 */
void OnMsgName_DataFrame1(DataFrame1 RxMsg)
{
/* TODO */
}/* End BUSMASTER generated function - OnMsgName_DataFrame1 */
/* Start BUSMASTER generated function - OnTimer_incGearPos_1000 */
void OnTimer_incGearPos_1000( )
{
/* Not used - phase control is in 10ms timer */
}/* End BUSMASTER generated function - OnTimer_incGearPos_1000 */
