/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.2.2] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
STCAN_MSG tx;
unsigned int RPM, i;
unsigned int SPD,GEAR;
float THW,THA,OT,BATTV,OP,LA1,MAP;
DataFrame1 sMsgStruct_Frame1;
DataFrame2 sMsgStruct_Frame2;
DataFrame3 sMsgStruct_Frame3;
DataFrame4 sMsgStruct_Frame4;
DataFrame5 sMsgStruct_Frame5;
DataFrame6 sMsgStruct_Frame6;
/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnTimer_updateTimeTick10ms_10( );
void OnMsgName_DataFrame1(DataFrame1 RxMsg);
GCC_EXTERN void GCC_EXPORT OnMsgName_DataFrame1_Wrapper(STCAN_MSG RxMsg);
GCC_EXTERN void GCC_EXPORT OnTimer_incGearPos_1000( );
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER Function Wrapper Prototype  */
void OnMsgName_DataFrame1_Wrapper(STCAN_MSG RxMsg){ OnMsgName_DataFrame1(&RxMsg); }
/* End BUSMASTER Function Wrapper Prototype  */


/* Start BUSMASTER generated function - OnTimer_updateTimeTick10ms_10 */
void OnTimer_updateTimeTick10ms_10( )
{
/* TODO */

/*tx.id = 0x3e8;
tx.dlc=8;
tx.data[0] = (RPM>>8);
tx.data[1] = 0xFF&RPM;*/

sMsgStruct_Frame1.RPM = RPM;
sMsgStruct_Frame1.IntakeAirTemperature = THA;
sMsgStruct_Frame1.ManifolePressure = MAP;
sMsgStruct_Frame2.EngineTemp = THW;
sMsgStruct_Frame2.Lambda1 = LA1;



sMsgStruct_Frame3.OilTemp = OT;
sMsgStruct_Frame4.OilPressure = OP;
sMsgStruct_Frame4.BatteryVoltage = BATTV;

sMsgStruct_Frame5.GroundSpeed = SPD;
sMsgStruct_Frame6.GearPosition = GEAR;




SendMsg(sMsgStruct_Frame1);
SendMsg(sMsgStruct_Frame2);
SendMsg(sMsgStruct_Frame3);
SendMsg(sMsgStruct_Frame4);
SendMsg(sMsgStruct_Frame5);
SendMsg(sMsgStruct_Frame6);



MAP = MAP +0.4;
LA1 = LA1+0.2;
THW = THW +0.1;
THA = THA +0.2;
OT = OT + 0.3;
OP = OP +1;
BATTV = BATTV +0.15;

if(i == 0){
	RPM =RPM + 100;
	if(RPM >= 7000){
		i=1;
	}
}
else if(i == 1){
	RPM =RPM - 100;
	if(RPM <= 4000){
		i=2;
	}
}
else if(i == 2){
	RPM =RPM + 50;
	if(RPM >= 7500){
		i=3;
	}
}
else if(i == 3){
	RPM =RPM - 100;
	if(RPM <= 4500){
		i=4;
	}
}
else if(i == 4){
	RPM =RPM + 20;
	if(RPM >= 8000){
		i=5;
	}
}
else if(i == 5){
	RPM =RPM - 100;
	if(RPM <= 1000){
		i=0;
	}
}
}/* End BUSMASTER generated function - OnTimer_updateTimeTick10ms_10 */
/* Start BUSMASTER generated function - OnMsgName_DataFrame1 */
void OnMsgName_DataFrame1(DataFrame1 RxMsg)
{
/* TODO */
}/* End BUSMASTER generated function - OnMsgName_DataFrame1 */
/* Start BUSMASTER generated function - OnTimer_incGearPos_1000 */
void OnTimer_incGearPos_1000( )
{
/* TODO */
GEAR = GEAR +1;
SPD = SPD +5;
}/* End BUSMASTER generated function - OnTimer_incGearPos_1000 */
