################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
LINKER_SCRIPT := 
SX_SRCS := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
X_SRCS := 
SRC_SRCS := 
X_UPPER_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
PRINT_SIZE := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
LST := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
OBJCOPY := 
JMP_UPPER_DEPS := 
PP_DEPS := 
SX_DEPS := 
ASM_UPPER_DEPS := 
OBJS := 
SX_UPPER_DEPS := 
ASM_DEPS := 
LIBRARY_GENERATOR_OUTPUTTYPE_OUTPUTS := 
MAP := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
aw/Resource/Font \
aw/Resource/Image \
aw/Resource/Text \
aw/Source \
aw/Source/CustomCode \
aw/Source/Generated \
src \
src/smc_gen/Config_MTU0 \
src/smc_gen/Config_MTU1 \
src/smc_gen/Config_MTU3 \
src/smc_gen/Config_MTU8 \
src/smc_gen/Config_PORT \
src/smc_gen/Config_RIIC0 \
src/smc_gen/Config_RIIC1 \
src/smc_gen/Config_RTC \
src/smc_gen/Config_S12AD0 \
src/smc_gen/general \
src/smc_gen/r_bsp/board/generic_rx72n \
src/smc_gen/r_bsp/mcu/all \
src/smc_gen/r_bsp/mcu/rx72n \
src/smc_gen/r_can_rx/src \
src/smc_gen/r_cmt_rx/src \
src/smc_gen/r_dmaca_rx/src \
src/smc_gen/r_dmaca_rx/src/targets/rx72n \
src/smc_gen/r_drw2d_rx/src/rx \
src/smc_gen/r_drw2d_rx/src/tes \
src/smc_gen/r_emwin_rx/lib/Config \
src/smc_gen/r_emwin_rx/src \
src/smc_gen/r_glcdc_rx/src \
src/smc_gen/r_glcdc_rx/src/targets/rx72n \
src/smc_gen/r_gpio_rx/src \
src/smc_gen/r_gpio_rx/src/targets/rx72n \
src/smc_gen/r_pincfg \

